### ISSUE TITLE
Dppl fails with beta09 due to libsycl.so.2 import error

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/dpctl#58] opened 2020-09-22 22:47 UTC
Dppl fails with the latest compiler in beta09 since it is looking for "libsycl.so.2" file. In beta09 "libsycl.so.2" is not present. Instead there is "libsycl.so" file which should be used by dppl. A temporary fix is to create a soft link between libsycl.so.2 and libsycl.so.

>>> import dppl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localdisk/work/adarshyoga/software/miniconda3/envs/build-env/lib/python3.7/site-packages/dppl/__init__.py", line 49, in <module>
    from ._sycl_core import *
ImportError: libsycl.so.2: cannot open shared object file: No such file or directory

**Comment by PokhodenkoSA** [comment] 2020-09-23 09:57
As I understand beta09 has a patched version with `libsycl.so.3` available instead of `libsycl.so.2`. If you use dppl from package downloaded from channels then it is possible that it was compiled with beta09 without patch.
Try to download the newer version of PyDPPL or recompile the package locally.

**Comment by oleksandr-pavlyk** [comment] 2020-09-23 15:15
This error indicates that you are using dpctl built with beta08 but running it with beta09 activated. Rebuilding dpctl with beta09 should fix the issue.

**Comment by diptorupd** [comment] 2020-09-26 18:13
I have been using beta09 and the `build_for_develop.sh` script without issue on Ubuntu. Please check your oneAPI install and follow @oleksandr-pavlyk 's advise to see if it resolve the issue. 

Closing for now. Please reopen if the issue is not resolved after a clean install of oneAPI beta 09.

**Comment by adarshyoga** [comment] 2020-10-02 03:06
This error is occurring on customer build  we have provided to Argonne. After installing pydppl, "import pydppl" fails with the same error.
>>> import dppl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adarshyoga/.conda/envs/build-env/lib/python3.7/site-packages/dppl/__init__.py", line 50, in <module>
    from ._oneapi_interface import *
ImportError: libsycl.so.2: cannot open shared object file: No such file or directory

**Comment by oleksandr-pavlyk** [comment] 2020-10-02 13:45
@Adarsh It means the that build provided to the customer has been compiled with the compiler older than the one installed on their machine. The solution would be to recompile the package.

**Comment by PokhodenkoSA** [comment] 2020-10-02 13:51
This situation could be more interesting.
I think PyDPPL was built with oneAPI beta09 with libsycl.so.2 and then compiler was updated with libsycl.so.3 and PyDPPL package was not rebuilt.

**Comment by diptorupd** [comment] 2020-10-22 04:01
@adarshyoga @reazulhoque @PokhodenkoSA is this still an issue?

**Comment by PokhodenkoSA** [comment] 2020-10-22 07:45
I think the issue is not actual. Reason is clean - mismatch of compiler which have built dpCtl and the compiler installed in system.

**Closed by PokhodenkoSA** 2020-10-22 07:45 UTC
Labels: bug
