### ISSUE TITLE
Vector implementations don`t work for elementwise functions 

### ISSUE THREAD

**Issue by vlad-perevezentsev** [IntelPython/dpctl#1236] opened 2023-06-09 19:25 UTC
If we replace equality operation(`==`) with inequality operation(`!=`) for vectors and pass the same types that are not complex so `supports_vec` is true, we get equality results. 

equal.hpp
```
resT operator()(const argT1 &in1, const argT2 &in2)
    {
        return (in1 == in2);
    }
template <int vec_sz>
    sycl::vec<resT, vec_sz> operator()(const sycl::vec<argT1, vec_sz> &in1,
                                       const sycl::vec<argT2, vec_sz> &in2)
    {
        auto tmp = (in1 != in2);
...
```
test.py
```
import dpctl.tensor as dpt

_all_dtypes = [
    "b1",
    "i1",
    "u1",
    "i2",
    "u2",
    "i4",
    "u4",
    "i8",
    "u8",
    "f2",
    "f4",
]
for dtype in _all_dtypes:
    a = dpt.asarray([-2,-1,0,1,2,3], dtype=dtype)
    print(dpt.equal(a,a))

#run
python test.py

[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
```

**Comment by ndgrigorian** [comment] 2023-06-23 19:10
After some testing, I have determined that the vector overloads do work.
In some cases, the maximum sub-group size (or the length of the input) will disable them. I suspect this was caused by one or the other.
I am closing this issue.

**Closed by ndgrigorian** 2023-06-23 19:10 UTC
Labels: bug
