### ISSUE TITLE
`test_atan2.py` fails with the latest version of the compiler 

### ISSUE THREAD

**Issue by vlad-perevezentsev** [IntelPython/dpctl#1402] opened 2023-09-18 11:01 UTC
Most tests from `dpctl/tests/elementwise/test_atan2.py` fall with `RuntumeError`.
This behavior was detected with the latest version of the compiler (dpcpp-cpp-rt 2024.0prerelease0  intel_49547)
On `gen9` the error is raised immediately during file run.
On `Iris Xe` freeze happens. 
I have only tested on linux

```
          if src1.shape != res_shape:
                src1 = dpt.broadcast_to(src1, res_shape)
            if src2.shape != res_shape:
                src2 = dpt.broadcast_to(src2, res_shape)
>           ht_binary_ev, binary_ev = self.binary_fn_(
                src1=src1, src2=src2, dst=out, sycl_queue=exec_q
            )
E           RuntimeError: The program was built for 1 devices
E           Build program log for 'Intel(R) UHD Graphics':
E           IGC: internal compiler error
E            -11 (PI_ERROR_BUILD_PROGRAM_FAILURE) -11 (PI_ERROR_BUILD_PROGRAM_FAILURE)

dpctl/tensor/_elementwise_common.py:614: RuntimeError
...
================== 169 failed, 32 passed in 13.11s ============================

```

**Comment by oleksandr-pavlyk** [comment] 2023-09-18 17:41
Please provide an actionable reproducer

**Comment by oleksandr-pavlyk** [comment] 2023-09-21 20:16
This issue was caused by old driver. Updating the driver to the latest release noted in https://dgpu-docs.intel.com/releases/index.html resolved the issue.

Closing

**Closed by oleksandr-pavlyk** 2023-09-21 20:16 UTC
