### ISSUE TITLE
Cannot use the dpctl follow the example

### ISSUE THREAD

**Issue by chengjunlu** [IntelPython/dpctl#935] opened 2022-10-17 08:48 UTC
I cannot reproduce the example step by step with the latest dpctl.

Here is my dpctl version:
0.11.3
And here is the headers in the dpctl:
``` Config                      dpctl_sycl_context_interface.h          dpctl_sycl_enum_types.h          dpctl_sycl_platform_manager.h   dpctl_sycl_types.h          Support
dpctl_data_types.h          dpctl_sycl_device_interface.h           dpctl_sycl_event_interface.h     dpctl_sycl_program_interface.h  dpctl_sycl_usm_interface.h
dpctl_error_handler_type.h  dpctl_sycl_device_manager.h             dpctl_sycl_kernel_interface.h    dpctl_sycl_queue_interface.h    dpctl_utils.h
dpctl_service.h             dpctl_sycl_device_selector_interface.h  dpctl_sycl_platform_interface.h  dpctl_sycl_queue_manager.h      dpctl_vector.h
```

But I didn't find these required headers in FindDpctl.cmake. 

`dpctl_capi.h` `dpctl4pybind11.hpp` `dpctl_sycl_interface.h`

Where can I find the instruction to use the dpctl for SYCL pybind?

**Comment by oleksandr-pavlyk** [comment] 2022-10-17 16:35
This is a duplicate of #808. The required header was added after 0.12 was released in #685. 

Please use the latest dpctl=0.13 which is available from conda. 

@xaleryb Do you know why dpctl on PyPI is so out of date?

**Closed** 2022-10-17 17:08 UTC
