### ISSUE TITLE
Swap of two elements in usm_ndarray with temporary variable works wrong

### ISSUE THREAD

**Issue by LukichevaPolina** [IntelPython/dpctl#594] opened 2021-09-24 12:16 UTC
Reproducer:
```python
import dpctl.tensor as dpt
import numpy as np

Xnp = np.arange(2)
X = dpt.from_numpy(Xnp)

print(dpt.to_numpy(X))

temp = X[0]
X[0] = X[1]
X[1] = temp

print(dpt.to_numpy(X))
```
Output:
```
[0 1]
[1 1]
```
Version of dpctl: `0.10.0rc2+1.gf2a12e1`

**Comment by oleksandr-pavlyk** [comment] 2021-09-24 13:19
Not a bug. The `X[0]` returns a 0d **view**, and so assignment `X[0] = X[1]` modifies the memory referenced by `temp`. 

The same thing in NumPy:

```
In [1]: import numpy as np

In [2]: X = np.arange(2)

In [3]: getitem_view = lambda X, i: X[i:i+1]

In [4]: temp = getitem_view(X, 0)

In [5]: X[0] = X[1]

In [6]: X[1] = temp

In [7]: X
Out[7]: array([1, 1])
``` 

NumPy introduced scalars to make this work, where `X[0]` returns a NumPy scalar, rather than 0d array with a view, thus making a copy. 

To fix the issue, you can modify your code as follows:

```python
import dpctl.tensor as dpt
import numpy as np

Xnp = np.arange(2)
X = dpt.from_numpy(Xnp)

print(dpt.to_numpy(X))

temp = dpt.usm_ndarray(tuple(), dtype=X.dtype)
temp[()] = X[0]  # make a copy
X[0] = X[1]
X[1] = temp

print(dpt.to_numpy(X))
```

which gives

```
In [8]: import dpctl.tensor as dpt
   ...: import numpy as np
   ...:
   ...: Xnp = np.arange(2)
   ...: X = dpt.from_numpy(Xnp)
   ...:
   ...: print(dpt.to_numpy(X))
   ...:
   ...: temp = dpt.usm_ndarray(tuple(), dtype=X.dtype)
   ...: temp[()] = X[0]  # make a copy
   ...: X[0] = X[1]
   ...: X[1] = temp
   ...:
   ...: print(dpt.to_numpy(X))
[0 1]
[1 0]
```

**Comment by diptorupd** [comment] 2021-10-06 02:19
@oleksandr-pavlyk @LukichevaPolina Should the ticket be closed?

**Comment by oleksandr-pavlyk** [comment] 2021-11-04 20:32
Note that `cupy` behaves exactly the same way:

```
In [1]: import cupy

In [2]: cupy.__version__
Out[2]: '9.5.0'

In [3]: X = cupy.arange(2)

In [4]: temp = X[0]
   ...: X[0] = X[1]
   ...: X[1] = temp

In [5]: X
Out[5]: array([1, 1])
```

**Comment by diptorupd** [comment] 2022-04-06 01:42
closing based on @oleksandr-pavlyk's last comment. Please reopen if needed.

**Closed by diptorupd** 2022-04-06 01:42 UTC
Labels: tensor
